export enum EleccionEstado {
  BORRADOR = 'BORRADOR',
  CONFIGURADA = 'CONFIGURADA', //OFFICIALIZED
  ABIERTA = 'ABIERTA',
  CERRADA = 'CERRADA',
  ESCRUTADA = 'ESCRUTADA',
  ARCHIVADA = 'ARCHIVADA',
}
