export enum TipoEventoAudit {
  ACCESO_DENEGADO = 'ACCESO_DENEGADO',
  LOGIN = 'LOGIN',
  CONFIG_MODIFICADA = 'CONFIG_MODIFICADA',
  PADRON_CARGADO = 'PADRON_CARGADO',
  COMICIO_ABIERTO = 'COMICIO_ABIERTO',
  COMICIO_CERRADO = 'COMICIO_CERRADO',
}
