export enum TipoEventoAudit {
  ACCESO_DENEGADO = 'ACCESO_DENEGADO',
  LOGIN = 'LOGIN',
  CONFIG_MODIFICADA = 'CONFIG_MODIFICADA',
  PADRON_CARGADO = 'PADRON_CARGADO',
  COMICIO_ABIERTO = 'COMICIO_ABIERTO',
  COMICIO_CERRADO = 'COMICIO_CERRADO',
  /** VOTAR-322: archivado off-chain de un comicio CERRADA. */
  COMICIO_ARCHIVADO = 'COMICIO_ARCHIVADO',
  /** Sufragio anónimo: sin IP/UA/session/votanteHash (VOTAR-379). */
  VOTO_EMITIDO = 'VOTO_EMITIDO',
}
